@startuml Sequenzdiagramm

actor Gast

boundary AutoGetController
control AutoReadService
database auto

Gast -> AutoGetController : GET /auto/:id
AutoGetController -> AutoReadService: findById()
AutoReadService -> auto: [TypeORM] findOne()

@enduml
